name: Build

on: [push]

env:
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x86

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -t:restore -p:Configuration=${{env.BUILD_CONFIGURATION}} -p:Platform=${{env.BUILD_PLATFORM}} -p:RestorePackagesConfig=true

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -t:rebuild -p:Configuration=${{env.BUILD_CONFIGURATION}} -p:Platform=${{env.BUILD_PLATFORM}} -m

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: PinToTop
        path: Release/PinToTop.exe
